---
listen: "127.0.0.1:5000"
github:
  v3_api_url: "https://api.github.com/"
  app:
    integration_id: 123456789
    webhook_secret: "supersecret"
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      aaabbbcccxxxyyyzzz
      -----END RSA PRIVATE KEY-----
